export enum AuthorizedType {
  Master = 'isMaster',
  Default = 'isDefault',
  CheckLiveStream = 'enableCheckLiveStream',
  ManagingSticker = 'enableManagingSticker',
  ManagingTTS = 'enableManagingTTS',
  ManagingSound = 'enableManagingSound',
  NoticeGNB = 'enableNoticeGNB',
  NoticeBanner = 'enableNoticeBanner',
  ReadUserList = 'enableReadUserList',
  ReadChargingHistory = 'enableReadChargingHistory',
  ReadDonationHistory = 'enableReadDonationHistory',
  ManagingCash = 'enableManagingCash',
  ManagingSettlement = 'enableManagingSettlement',
}
